package com.example.john.androidclient;

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.widget.Button;
import android.widget.ImageView;

public class GUIActivity extends AppCompatActivity {

    Button button;
    int val = 0;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_gui);
        final String addr = "10.0.2.2";
        final int port = 2345;
        int valarr[];
        valarr = new int[160];
        //I know there is a better way to do this but I am way crunched for time so I wrote a Python script that would generate each of these lines because I just needed a working demo
        ImageView iv1 = (ImageView) findViewById(R.id.imageView1);
        ImageView iv2 = (ImageView) findViewById(R.id.imageView2);
        ImageView iv3 = (ImageView) findViewById(R.id.imageView3);
        ImageView iv4 = (ImageView) findViewById(R.id.imageView4);
        ImageView iv5 = (ImageView) findViewById(R.id.imageView5);
        ImageView iv6 = (ImageView) findViewById(R.id.imageView6);
        ImageView iv7 = (ImageView) findViewById(R.id.imageView7);
        ImageView iv8 = (ImageView) findViewById(R.id.imageView8);
        ImageView iv9 = (ImageView) findViewById(R.id.imageView9);
        ImageView iv10 = (ImageView) findViewById(R.id.imageView10);
        ImageView iv11 = (ImageView) findViewById(R.id.imageView11);
        ImageView iv12 = (ImageView) findViewById(R.id.imageView12);
        ImageView iv13 = (ImageView) findViewById(R.id.imageView13);
        ImageView iv14 = (ImageView) findViewById(R.id.imageView14);
        ImageView iv15 = (ImageView) findViewById(R.id.imageView15);
        ImageView iv16 = (ImageView) findViewById(R.id.imageView16);
        ImageView iv17 = (ImageView) findViewById(R.id.imageView17);
        ImageView iv18 = (ImageView) findViewById(R.id.imageView18);
        ImageView iv19 = (ImageView) findViewById(R.id.imageView19);
        ImageView iv20 = (ImageView) findViewById(R.id.imageView20);
        ImageView iv21 = (ImageView) findViewById(R.id.imageView21);
        ImageView iv22 = (ImageView) findViewById(R.id.imageView22);
        ImageView iv23 = (ImageView) findViewById(R.id.imageView23);
        ImageView iv24 = (ImageView) findViewById(R.id.imageView24);
        ImageView iv25 = (ImageView) findViewById(R.id.imageView25);
        ImageView iv26 = (ImageView) findViewById(R.id.imageView26);
        ImageView iv27 = (ImageView) findViewById(R.id.imageView27);
        ImageView iv28 = (ImageView) findViewById(R.id.imageView28);
        ImageView iv29 = (ImageView) findViewById(R.id.imageView29);
        ImageView iv30 = (ImageView) findViewById(R.id.imageView30);
        ImageView iv31 = (ImageView) findViewById(R.id.imageView31);
        ImageView iv32 = (ImageView) findViewById(R.id.imageView32);
        ImageView iv33 = (ImageView) findViewById(R.id.imageView33);
        ImageView iv34 = (ImageView) findViewById(R.id.imageView34);
        ImageView iv35 = (ImageView) findViewById(R.id.imageView35);
        ImageView iv36 = (ImageView) findViewById(R.id.imageView36);
        ImageView iv37 = (ImageView) findViewById(R.id.imageView37);
        ImageView iv38 = (ImageView) findViewById(R.id.imageView38);
        ImageView iv39 = (ImageView) findViewById(R.id.imageView39);
        ImageView iv40 = (ImageView) findViewById(R.id.imageView40);
        ImageView iv41 = (ImageView) findViewById(R.id.imageView41);
        ImageView iv42 = (ImageView) findViewById(R.id.imageView42);
        ImageView iv43 = (ImageView) findViewById(R.id.imageView43);
        ImageView iv44 = (ImageView) findViewById(R.id.imageView44);
        ImageView iv45 = (ImageView) findViewById(R.id.imageView45);
        ImageView iv46 = (ImageView) findViewById(R.id.imageView46);
        ImageView iv47 = (ImageView) findViewById(R.id.imageView47);
        ImageView iv48 = (ImageView) findViewById(R.id.imageView48);
        ImageView iv49 = (ImageView) findViewById(R.id.imageView49);
        ImageView iv50 = (ImageView) findViewById(R.id.imageView50);
        ImageView iv51 = (ImageView) findViewById(R.id.imageView51);
        ImageView iv52 = (ImageView) findViewById(R.id.imageView52);
        ImageView iv53 = (ImageView) findViewById(R.id.imageView53);
        ImageView iv54 = (ImageView) findViewById(R.id.imageView54);
        ImageView iv55 = (ImageView) findViewById(R.id.imageView55);
        ImageView iv56 = (ImageView) findViewById(R.id.imageView56);
        ImageView iv57 = (ImageView) findViewById(R.id.imageView57);
        ImageView iv58 = (ImageView) findViewById(R.id.imageView58);
        ImageView iv59 = (ImageView) findViewById(R.id.imageView59);
        ImageView iv60 = (ImageView) findViewById(R.id.imageView60);
        ImageView iv61 = (ImageView) findViewById(R.id.imageView61);
        ImageView iv62 = (ImageView) findViewById(R.id.imageView62);
        ImageView iv63 = (ImageView) findViewById(R.id.imageView63);
        ImageView iv64 = (ImageView) findViewById(R.id.imageView64);
        ImageView iv65 = (ImageView) findViewById(R.id.imageView65);
        ImageView iv66 = (ImageView) findViewById(R.id.imageView66);
        ImageView iv67 = (ImageView) findViewById(R.id.imageView67);
        ImageView iv68 = (ImageView) findViewById(R.id.imageView68);
        ImageView iv69 = (ImageView) findViewById(R.id.imageView69);
        ImageView iv70 = (ImageView) findViewById(R.id.imageView70);
        ImageView iv71 = (ImageView) findViewById(R.id.imageView71);
        ImageView iv72 = (ImageView) findViewById(R.id.imageView72);
        ImageView iv73 = (ImageView) findViewById(R.id.imageView73);
        ImageView iv74 = (ImageView) findViewById(R.id.imageView74);
        ImageView iv75 = (ImageView) findViewById(R.id.imageView75);
        ImageView iv76 = (ImageView) findViewById(R.id.imageView76);
        ImageView iv77 = (ImageView) findViewById(R.id.imageView77);
        ImageView iv78 = (ImageView) findViewById(R.id.imageView78);
        ImageView iv79 = (ImageView) findViewById(R.id.imageView79);
        ImageView iv80 = (ImageView) findViewById(R.id.imageView80);
        ImageView iv81 = (ImageView) findViewById(R.id.imageView81);
        ImageView iv82 = (ImageView) findViewById(R.id.imageView82);
        ImageView iv83 = (ImageView) findViewById(R.id.imageView83);
        ImageView iv84 = (ImageView) findViewById(R.id.imageView84);
        ImageView iv85 = (ImageView) findViewById(R.id.imageView85);
        ImageView iv86 = (ImageView) findViewById(R.id.imageView86);
        ImageView iv87 = (ImageView) findViewById(R.id.imageView87);
        ImageView iv88 = (ImageView) findViewById(R.id.imageView88);
        ImageView iv89 = (ImageView) findViewById(R.id.imageView89);
        ImageView iv90 = (ImageView) findViewById(R.id.imageView90);
        ImageView iv91 = (ImageView) findViewById(R.id.imageView91);
        ImageView iv92 = (ImageView) findViewById(R.id.imageView92);
        ImageView iv93 = (ImageView) findViewById(R.id.imageView93);
        ImageView iv94 = (ImageView) findViewById(R.id.imageView94);
        ImageView iv95 = (ImageView) findViewById(R.id.imageView95);
        ImageView iv96 = (ImageView) findViewById(R.id.imageView96);
        ImageView iv97 = (ImageView) findViewById(R.id.imageView97);
        ImageView iv98 = (ImageView) findViewById(R.id.imageView98);
        ImageView iv99 = (ImageView) findViewById(R.id.imageView99);
        ImageView iv100 = (ImageView) findViewById(R.id.imageView100);
        ImageView iv101 = (ImageView) findViewById(R.id.imageView101);
        ImageView iv102 = (ImageView) findViewById(R.id.imageView102);
        ImageView iv103 = (ImageView) findViewById(R.id.imageView103);
        ImageView iv104 = (ImageView) findViewById(R.id.imageView104);
        ImageView iv105 = (ImageView) findViewById(R.id.imageView105);
        ImageView iv106 = (ImageView) findViewById(R.id.imageView106);
        ImageView iv107 = (ImageView) findViewById(R.id.imageView107);
        ImageView iv108 = (ImageView) findViewById(R.id.imageView108);
        ImageView iv109 = (ImageView) findViewById(R.id.imageView109);
        ImageView iv110 = (ImageView) findViewById(R.id.imageView110);
        ImageView iv111 = (ImageView) findViewById(R.id.imageView111);
        ImageView iv112 = (ImageView) findViewById(R.id.imageView112);
        ImageView iv113 = (ImageView) findViewById(R.id.imageView113);
        ImageView iv114 = (ImageView) findViewById(R.id.imageView114);
        ImageView iv115 = (ImageView) findViewById(R.id.imageView115);
        ImageView iv116 = (ImageView) findViewById(R.id.imageView116);
        ImageView iv117 = (ImageView) findViewById(R.id.imageView117);
        ImageView iv118 = (ImageView) findViewById(R.id.imageView118);
        ImageView iv119 = (ImageView) findViewById(R.id.imageView119);
        ImageView iv120 = (ImageView) findViewById(R.id.imageView120);
        ImageView iv121 = (ImageView) findViewById(R.id.imageView121);
        ImageView iv122 = (ImageView) findViewById(R.id.imageView122);
        ImageView iv123 = (ImageView) findViewById(R.id.imageView123);
        ImageView iv124 = (ImageView) findViewById(R.id.imageView124);
        ImageView iv125 = (ImageView) findViewById(R.id.imageView125);
        ImageView iv126 = (ImageView) findViewById(R.id.imageView126);
        ImageView iv127 = (ImageView) findViewById(R.id.imageView127);
        ImageView iv128 = (ImageView) findViewById(R.id.imageView128);
        ImageView iv129 = (ImageView) findViewById(R.id.imageView129);
        ImageView iv130 = (ImageView) findViewById(R.id.imageView130);
        ImageView iv131 = (ImageView) findViewById(R.id.imageView131);
        ImageView iv132 = (ImageView) findViewById(R.id.imageView132);
        ImageView iv133 = (ImageView) findViewById(R.id.imageView133);
        ImageView iv134 = (ImageView) findViewById(R.id.imageView134);
        ImageView iv135 = (ImageView) findViewById(R.id.imageView135);
        ImageView iv136 = (ImageView) findViewById(R.id.imageView136);
        ImageView iv137 = (ImageView) findViewById(R.id.imageView137);
        ImageView iv138 = (ImageView) findViewById(R.id.imageView138);
        ImageView iv139 = (ImageView) findViewById(R.id.imageView139);
        ImageView iv140 = (ImageView) findViewById(R.id.imageView140);
        ImageView iv141 = (ImageView) findViewById(R.id.imageView141);
        ImageView iv142 = (ImageView) findViewById(R.id.imageView142);
        ImageView iv143 = (ImageView) findViewById(R.id.imageView143);
        ImageView iv144 = (ImageView) findViewById(R.id.imageView144);
        ImageView iv145 = (ImageView) findViewById(R.id.imageView145);
        ImageView iv146 = (ImageView) findViewById(R.id.imageView146);
        ImageView iv147 = (ImageView) findViewById(R.id.imageView147);
        ImageView iv148 = (ImageView) findViewById(R.id.imageView148);
        ImageView iv149 = (ImageView) findViewById(R.id.imageView149);
        ImageView iv150 = (ImageView) findViewById(R.id.imageView150);
        ImageView iv151 = (ImageView) findViewById(R.id.imageView151);
        ImageView iv152 = (ImageView) findViewById(R.id.imageView152);
        ImageView iv153 = (ImageView) findViewById(R.id.imageView153);
        ImageView iv154 = (ImageView) findViewById(R.id.imageView154);
        ImageView iv155 = (ImageView) findViewById(R.id.imageView155);
        ImageView iv156 = (ImageView) findViewById(R.id.imageView156);
        ImageView iv157 = (ImageView) findViewById(R.id.imageView157);
        ImageView iv158 = (ImageView) findViewById(R.id.imageView158);
        ImageView iv159 = (ImageView) findViewById(R.id.imageView159);
        ImageView iv160 = (ImageView) findViewById(R.id.imageView160);
        ImageView[] ivs = {iv1,iv2,iv3,iv4,iv5,iv6,iv7,iv8,iv9,iv10,iv11,iv12,iv13,iv14,iv15,iv16,iv17,iv18,iv19,iv20,iv21,iv22,iv23,iv24,iv25,iv26,iv27,iv28,iv29,iv30,iv31,iv32,iv33,iv34,iv35,iv36,iv37,iv38,iv39,iv40,iv41,iv42,iv43,iv44,iv45,iv46,iv47,iv48,iv49,iv50,iv51,iv52,iv53,iv54,iv55,iv56,iv57,iv58,iv59,iv60,iv61,iv62,iv63,iv64,iv65,iv66,iv67,iv68,iv69,iv70,iv71,iv72,iv73,iv74,iv75,iv76,iv77,iv78,iv79,iv80,iv81,iv82,iv83,iv84,iv85,iv86,iv87,iv88,iv89,iv90,iv91,iv92,iv93,iv94,iv95,iv96,iv97,iv98,iv99,iv100,iv101,iv102,iv103,iv104,iv105,iv106,iv107,iv108,iv109,iv110,iv111,iv112,iv113,iv114,iv115,iv116,iv117,iv118,iv119,iv120,iv121,iv122,iv123,iv124,iv125,iv126,iv127,iv128,iv129,iv130,iv131,iv132,iv133,iv134,iv135,iv136,iv137,iv138,iv139,iv140,iv141,iv142,iv143,iv144,iv145,iv146,iv147,iv148,iv149,iv150,iv151,iv152,iv153,iv154,iv155,iv156,iv157,iv158,iv159,iv160};
        com.example.john.androidclient.Client myClient = new com.example.john.androidclient.Client(addr, port, ivs,valarr);
        myClient.execute();

    }
}
